/**
 * Static require() maps for bundled content media, generated by
 * `npm run content` from content/media/{audio,images}. Do not edit by
 * hand — Metro needs literal require() calls (no dynamic paths), so this
 * file lists one per media file that actually exists.
 */

export const audio: Record<string, number> = {

};

export const images: Record<string, number> = {

};
